/* Pokemon category owns its filters, cache and watchlist. */
(()=>{
const el=id=>document.getElementById(id), safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cash=v=>typeof v==='number'&&Number.isFinite(v)?'$'+v.toFixed(2):'—';
let cards=[], catalogue=[], matches=[], page=1, watched=new Set(), mode='featured', loaded=false, stamp='', selected=null, featuredIds=new Set();
try{watched=new Set(JSON.parse(localStorage.getItem('pokemon-watch-v1')||'[]'))}catch{}
function prices(c){const t=c.pricing?.tcgplayer;return t?.unit==='USD'?Object.entries(t).filter(([k,v])=>v&&typeof v==='object'&&k!=='updated'):[]}
function price(c){return prices(c).find(([k,v])=>typeof v.marketPrice==='number')?.[1]?.marketPrice??null}
function link(c){const p=prices(c).find(([k,v])=>v.productId)?.[1]?.productId;return p?'https://www.tcgplayer.com/product/'+encodeURIComponent(p):'https://www.tcgplayer.com/search/pokemon/product?productLineName=pokemon&q='+encodeURIComponent(c.name+' '+(c.set?.name||'')+' '+c.localId)+'&view=grid'}
function date(s){const d=new Date(s);return Number.isFinite(d.valueOf())?d.toLocaleString():'Unavailable'}
function image(c){return c.image?`<img class="thumb" src="${safe(c.image)}/low.webp" alt="${safe(c.name)}" loading="lazy">`:'<span class="thumb"></span>'}
async function read(path,key){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const r=await fetch(path,{cache:'no-store',signal:controller.signal});if(!r.ok)throw Error(r.status);const d=await r.json();try{localStorage.setItem(key,JSON.stringify(d))}catch{}return {...d,_cache:false}}catch(e){try{const d=JSON.parse(localStorage.getItem(key)||'null');if(d)return {...d,_cache:true}}catch{}throw e}finally{clearTimeout(timer)}}
async function load(){el('pkStatus').textContent='Checking Pokémon snapshots…';try{const d=await read('data/pokemon.json','pokemon-data-v1');cards=d.cards;featuredIds=new Set(cards.map(c=>c.id));stamp=d.checkedAt;loaded=true;el('pkStatus').textContent=`${cards.length} featured singles · ${d._cache?'Saved browser snapshot':'Snapshot checked'} ${date(stamp)} · ${cards.filter(c=>c._status==='retained').length} retained card records`;const sets=[...new Set(cards.map(c=>c.set?.name).filter(Boolean))].sort();el('pkSet').innerHTML='<option value="">All sets</option>'+sets.map(s=>`<option>${safe(s)}</option>`).join('');render()}catch{el('pkStatus').textContent='Pokémon snapshot unavailable. Retry refresh; catalogue search is still available.';el('pkRows').innerHTML='<tr><td colspan="7">No saved featured cards available.</td></tr>'}}
async function getCatalogue(){if(catalogue.length)return;el('pkStatus').textContent='Loading English catalogue…';try{const d=await read('data/pokemon-catalogue.json','pokemon-catalogue-v1');catalogue=d.cards;el('pkStatus').textContent=`${catalogue.length.toLocaleString()} English catalogue entries · ${d._cache?'Saved snapshot':'Checked'} ${date(d.checkedAt)}`;render()}catch{el('pkStatus').textContent='Catalogue unavailable. Try refresh.'}}
function render(){const q=el('pkSearch').value.trim().toLowerCase(),set=el('pkSet').value,min=el('pkMin').value,max=el('pkMax').value;const detailed=new Map(cards.map(c=>[c.id,c]));let list=mode==='catalogue'?catalogue.map(c=>detailed.get(c.id)||c):cards.filter(c=>featuredIds.has(c.id));matches=list.filter(c=>(!q||`${c.name} ${c.id} ${c.localId} ${c.set?.name||''}`.toLowerCase().includes(q))&&(!set||c.set?.name===set)&&(!el('pkWatchOnly').checked||watched.has(c.id))&&(min===''||(price(c)!==null&&price(c)>=Number(min)))&&(max===''||(price(c)!==null&&price(c)<=Number(max))));const sort=el('pkSort').value;matches.sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='set'?(a.set?.name||a.id).localeCompare(b.set?.name||b.id):price(a)===null?price(b)===null?0:1:price(b)===null?-1:sort==='low'?price(a)-price(b):price(b)-price(a));const pages=Math.max(1,Math.ceil(matches.length/40));page=Math.min(page,pages);el('pkCount').textContent=`${matches.length.toLocaleString()} results · ${watched.size} watched`;el('pkPage').textContent=`Page ${page} of ${pages}`;el('pkPrev').disabled=page===1;el('pkNext').disabled=page===pages;el('pkRows').innerHTML=matches.slice((page-1)*40,page*40).map(c=>`<tr><td><button class="btn" data-pk-watch="${safe(c.id)}" aria-label="${watched.has(c.id)?'Unwatch':'Watch'} ${safe(c.name)}">${watched.has(c.id)?'★':'☆'}</button></td><td><div class="cardcell">${image(c)}<div><button class="btn" data-pk-card="${safe(c.id)}">${safe(c.name)}</button><span class="sub">${safe(c.id)}</span></div></div></td><td>${safe(c.set?.name||'Open details for set')}</td><td>${safe(c.rarity||'—')}</td><td><b>${cash(price(c))}</b><span class="sub">${safe(prices(c).find(([k,v])=>v.marketPrice===price(c))?.[0]||'Open details for pricing')}</span></td><td>${safe(c.pricing?.tcgplayer?.updated?date(c.pricing.tcgplayer.updated):'—')}</td><td><a href="${safe(link(c))}" target="_blank" rel="noopener noreferrer">${prices(c).some(([k,v])=>v.productId)?'TCGplayer product':'TCGplayer search'} ↗</a></td></tr>`).join('')||'<tr><td colspan="7">No matching cards. Clear filters or switch to English catalogue.</td></tr>';el('pkRows').querySelectorAll('img').forEach(i=>i.onerror=()=>{i.style.opacity='.25';i.alt='Image unavailable'});}
async function detail(id){selected=id;const target=el('pkDetail');target.hidden=false;target.innerHTML='<div class="body">Loading card details…</div>';let c=cards.find(c=>c.id===id);try{if(!c){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const r=await fetch('https://api.tcgdex.net/v2/en/cards/'+encodeURIComponent(id),{signal:controller.signal});if(!r.ok)throw Error(r.status);c=await r.json();if(c.id!==id||!['Pokemon','Trainer','Energy'].includes(c.category))throw Error('Unexpected card');cards.push(c)}finally{clearTimeout(timer)}}if(selected!==id)return;target.innerHTML=`<div class="panel-head"><h2>${safe(c.name)} · ${safe(c.localId)}</h2><button class="btn" id="pkClose">Close</button></div><div class="body" style="display:flex;gap:20px;flex-wrap:wrap"><div>${c.image?`<img src="${safe(c.image)}/high.webp" alt="${safe(c.name)}" style="width:220px;max-width:100%;border-radius:12px">`:''}</div><div style="flex:1;min-width:240px"><h3>${safe(c.set?.name)} · ${safe(c.rarity)}</h3><p class="muted">${safe(c.illustrator||'')} · English · ${safe(c.id)}</p><div class="table-wrap"><table style="min-width:440px"><thead><tr><th>Finish</th><th>Market USD</th><th>Listed low USD</th><th>Listing</th></tr></thead><tbody>${prices(c).map(([k,v])=>`<tr><td>${safe(k)}</td><td>${cash(v.marketPrice)}</td><td>${cash(v.lowPrice)}</td><td>${v.productId?`<a href="https://www.tcgplayer.com/product/${encodeURIComponent(v.productId)}" target="_blank" rel="noopener noreferrer">Product ↗</a>`:'Unavailable'}</td></tr>`).join('')||'<tr><td colspan="4">USD price unavailable for this printing.</td></tr>'}</tbody></table></div><p class="muted">Price source updated: ${safe(date(c.pricing?.tcgplayer?.updated))}</p><div class="callout">Market is the source’s market price. Listed low is an asking price. Check the exact finish, condition and edition on the linked marketplace. Missing prices are never treated as zero.</div><p><a href="https://api.tcgdex.net/v2/en/cards/${encodeURIComponent(c.id)}" target="_blank" rel="noopener noreferrer">Card data source ↗</a></p></div></div>`;el('pkClose').onclick=()=>{selected=null;target.hidden=true};target.scrollIntoView({behavior:'smooth',block:'nearest'});render()}catch{if(selected===id)target.innerHTML='<div class="body">Details unavailable. Try opening the card again or use its TCGplayer search link.</div>'}}
el('pkRows').addEventListener('click',e=>{const w=e.target.closest('[data-pk-watch]'),c=e.target.closest('[data-pk-card]');if(w){const id=w.dataset.pkWatch;watched.has(id)?watched.delete(id):watched.add(id);try{localStorage.setItem('pokemon-watch-v1',JSON.stringify([...watched]))}catch{}render()}else if(c)detail(c.dataset.pkCard)});
for(const id of ['pkSearch','pkSet','pkSort','pkMin','pkMax','pkWatchOnly'])el(id).addEventListener('input',()=>{page=1;render()});
el('pkMode').onchange=async()=>{mode=el('pkMode').value;page=1;el('pkSet').value='';el('pkSet').disabled=mode==='catalogue';if(mode==='catalogue')await getCatalogue();render()};
el('pkPrev').onclick=()=>{page--;render()};el('pkNext').onclick=()=>{page++;render()};el('pkRefresh').onclick=async()=>{await load();if(mode==='catalogue'){catalogue=[];await getCatalogue()}};
el('pkReset').onclick=()=>{['pkSearch','pkSet','pkMin','pkMax'].forEach(id=>el(id).value='');el('pkWatchOnly').checked=false;page=1;render()};
el('pkExport').onclick=()=>{const quote=v=>'"'+String(v??'').replaceAll('"','""')+'"';const rows=[['Card','ID','Set','Rarity','Market USD','Source updated','TCGplayer'],...matches.map(c=>[c.name,c.id,c.set?.name,c.rarity,price(c),c.pricing?.tcgplayer?.updated,link(c)])];const blob=new Blob([rows.map(r=>r.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='pokemon-market-pulse.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
document.querySelector('[data-view="pokemon"]').addEventListener('click',()=>{if(!loaded)load()});
})();
