(()=>{
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>typeof v==='number'&&Number.isFinite(v)?'$'+v.toFixed(2):'—',rate=v=>'$'+v.toFixed(3),date=v=>{const d=new Date(v);return Number.isFinite(d.valueOf())?d.toLocaleString():'Unavailable'};
let data=null,filtered=[],watch=new Set(),busy=false;
try{watch=new Set(JSON.parse(localStorage.getItem('pokemon-bulk-watch-v1')||'[]'))}catch{}
function quote(){if(!data)return;const b=data.buyers[Number($('bulkBuyer').value)],r=b?.rates[Number($('bulkCategory').value)];const n=Math.max(0,Math.floor(Number($('bulkQty').value)||0)),shipping=Math.max(0,Number($('bulkShipping').value)||0);$('bulkQuote').textContent=r?`${n.toLocaleString()} cards × ${rate(r.usd)} = ${money(n*r.usd)} gross · ${money(n*r.usd-shipping)} after your entered shipping cost`:'No published category quote available.';}
function categories(){const b=data?.buyers[Number($('bulkBuyer').value)];$('bulkCategory').innerHTML=(b?.rates||[]).map((r,i)=>`<option value="${i}">${esc(r.category)} · ${rate(r.usd)} each</option>`).join('');$('bulkTerms').textContent=b?`${b.terms} Checked ${date(b.checkedAt)}${b.status==='retained'?' · retained snapshot; latest check failed':''}`:'';quote()}
function render(){if(!data)return;const q=$('bulkSearch').value.trim().toLowerCase(),kind=$('bulkKind').value;filtered=data.cards.filter(c=>(!q||`${c.name} ${c.card.set?.name||''} ${c.card.id} ${c.printings.map(p=>p.set+' '+p.number).join(' ')}`.toLowerCase().includes(q))&&(!kind||c.kind===kind)&&(!$('bulkWatched').checked||watch.has(c.name)));const sort=$('bulkSort').value;filtered.sort((a,b)=>sort==='copies'?b.copies-a.copies:sort==='archetypes'?b.archetypes.length-a.archetypes.length:sort==='name'?a.name.localeCompare(b.name):b.decks-a.decks||b.copies-a.copies);$('bulkCount').textContent=`${filtered.length} cards · ${watch.size} watched`;
$('bulkRows').innerHTML=filtered.map((c,i)=>`<tr><td>${i+1}</td><td><button class="btn" data-bulk-watch="${esc(c.name)}" aria-label="${watch.has(c.name)?'Unwatch':'Watch'} ${esc(c.name)}">${watch.has(c.name)?'★':'☆'}</button></td><td><div class="cardcell">${c.card.image?`<img class="thumb" src="${esc(c.card.image)}/low.webp" alt="${esc(c.name)}" loading="lazy">`:''}<div><button class="btn" data-bulk-card="${esc(c.card.id)}">${esc(c.name)}</button><span class="sub">${esc(c.kind)} · ${esc(c.card.rarity)} · ${esc(c.card.set?.name)} ${esc(c.card.localId)}</span><span class="sub">${c.card.metadataRetained?'Card metadata retained from prior check':''}</span></div></div></td><td><b>${c.pct.toFixed(1)}%</b><span class="sub">${c.decks} / ${data.totalDecklists} lists</span></td><td>${c.avgCopies.toFixed(2)}<span class="sub">per deck using this name</span></td><td><b>${c.archetypes.length}</b><details><summary style="cursor:pointer">View archetypes</summary><span class="sub">${c.archetypes.map(esc).join(', ')}</span></details></td><td>${money(c.displayedPrice)}<span class="sub">Limitless displayed USD</span></td><td><a href="${esc(c.cardUrl)}" target="_blank" rel="noopener noreferrer">Printing & usage ↗</a><details><summary style="cursor:pointer">${c.printings.length} printing(s)</summary>${c.printings.map(p=>`<a class="sub" href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">${esc(p.set)} ${esc(p.number)} · ${p.decks} lists</a>`).join('')}</details>${c.marketUrl?`<a class="sub" href="${esc(c.marketUrl)}" target="_blank" rel="noopener noreferrer">TCGplayer ↗</a>`:''}</td></tr>`).join('')||'<tr><td colspan="8">No matching cards. Clear filters or uncheck Watchlist only.</td></tr>';$('bulkRows').querySelectorAll('img').forEach(i=>i.onerror=()=>{i.alt='Image unavailable';i.style.opacity='.25'});
}
async function load(){if(busy)return;busy=true;$('bulkStatus').textContent='Checking bulk-demand snapshot…';const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);let cached=false;try{let d;try{const r=await fetch('data/pokemon-bulk.json',{cache:'no-store',signal:controller.signal});if(!r.ok)throw Error(r.status);d=await r.json();if(!Array.isArray(d.cards)||!d.totalDecklists)throw Error('Invalid snapshot');try{localStorage.setItem('pokemon-bulk-data-v1',JSON.stringify(d))}catch{}}catch(e){try{d=JSON.parse(localStorage.getItem('pokemon-bulk-data-v1')||'null')}catch{}if(!d)throw e;cached=true}data=d;const age=Date.now()-new Date(d.checkedAt).valueOf();$('bulkStatus').textContent=`${cached?'Saved browser snapshot · ':''}${d.status==='retained'?'Latest source check failed; retained data · ':''}${age>72*3600000?'Snapshot over 72 hours old · ':''}${d.cards.length} verified ordinary printings · ${d.totalDecklists.toLocaleString()} complete published decklists · checked ${date(d.checkedAt)}${d.issues?.length?' · '+d.issues.length+' source issue(s)':''}`;$('bulkEvents').innerHTML=d.events.map(e=>`<a class="source" href="${esc(e.url)}" target="_blank" rel="noopener noreferrer">${esc(e.name)} · ${esc(e.date)} · ${e.decklists} lists ↗</a>`).join('');$('bulkIssues').textContent=(d.issues||[]).join(' · ');$('bulkBuyer').innerHTML=d.buyers.map((b,i)=>`<option value="${i}">${esc(b.name)}${b.status==='retained'?' (retained)':''}</option>`).join('');$('bulkRates').innerHTML=d.buyers.map(b=>`<div class="panel"><div class="panel-head"><h3 style="margin:0">${esc(b.name)}</h3><a href="${esc(b.url)}" target="_blank" rel="noopener noreferrer">Buylist ↗</a></div><div class="body"><p class="muted">${esc(b.terms)}</p><p class="sub">Checked ${esc(date(b.checkedAt))}${b.status==='retained'?' · latest check failed, rates retained':''}</p><div class="table-wrap" style="max-height:360px"><table style="min-width:330px"><thead><tr><th>Category</th><th>USD / card</th><th>USD / 1,000</th></tr></thead><tbody>${b.rates.map(r=>`<tr><td>${esc(r.category)}</td><td>${rate(r.usd)}</td><td>${money(r.usd*1000)}</td></tr>`).join('')}</tbody></table></div></div></div>`).join('')||'<p class="muted">Buyer quotes unavailable.</p>';categories();render()}catch{$('bulkStatus').textContent='Bulk-demand snapshot unavailable. Retry Refresh bulk.';$('bulkRows').innerHTML='<tr><td colspan="8">No available snapshot.</td></tr>'}finally{busy=false;clearTimeout(timer)}}
for(const id of ['bulkSearch','bulkKind','bulkSort','bulkWatched'])$(id).addEventListener('input',render);
$('bulkRows').addEventListener('click',e=>{const w=e.target.closest('[data-bulk-watch]'),c=e.target.closest('[data-bulk-card]');if(w){const name=w.dataset.bulkWatch;watch.has(name)?watch.delete(name):watch.add(name);try{localStorage.setItem('pokemon-bulk-watch-v1',JSON.stringify([...watch]))}catch{}render()}else if(c){const row=data.cards.find(x=>x.card.id===c.dataset.bulkCard);if(row){showView('pokemon');document.dispatchEvent(new CustomEvent('pokemon-card-detail',{detail:row.card}))}}});
$('bulkRefresh').onclick=load;$('bulkBuyer').onchange=categories;$('bulkCategory').onchange=quote;$('bulkQty').oninput=quote;$('bulkShipping').oninput=quote;
$('bulkClear').onclick=()=>{$('bulkSearch').value='';$('bulkKind').value='';$('bulkWatched').checked=false;render()};
$('bulkExport').onclick=()=>{const csv=v=>'"'+String(v??'').replaceAll('"','""')+'"';const rows=[['Name','Representative printing','Type','Rarity','Published decks using name','Sample lists','Share percent','Average copies in using decks','Archetypes','Displayed USD price','Snapshot checked','Source'],...filtered.map(c=>[c.name,c.card.id,c.kind,c.card.rarity,c.decks,data.totalDecklists,c.pct,c.avgCopies,c.archetypes.length,c.displayedPrice,data.checkedAt,c.cardUrl])];const url=URL.createObjectURL(new Blob([rows.map(r=>r.map(csv).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='pokemon-bulk-demand.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
document.querySelector('[data-view="bulk"]').addEventListener('click',()=>{if(!data)load()});
})();
